[package]
name = "promotional-boost-contract"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
soroban-sdk = { version = "22.0.7" }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
