[package]
name = "airdrop-contract"
version = "0.1.0"
edition = "2024"

[lib]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
referral-contract = { path = "../referral-contract" }

