[package]
name = "crowdfunding-collective"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
soroban-sdk = "22.0.6"

[dev-dependencies]
soroban-sdk = { version = "22.0.6", features = ["testutils"] }
